export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const AUTH_USER = 'AUTH_USER';
export const UN_AUTH_USER = 'UN_AUTH_USER';

export const EMAIL_VALID = 'EMAIL_VALID';

export const AUTH_RESET = 'AUTH_RESET';
export const AUTH_RESET_SUCCESS = 'AUTH_RESET_SUCCESS';
export const AUTH_RESET_FAILURE = 'AUTH_RESET_FAILURE';

export const GET_ALL_USERS = 'GET_ALL_USERS';

export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE';

export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const GET_ALL_PROJECTS_SUCCESS = 'GET_ALL_PROJECTS_SUCCESS';
export const GET_ALL_PROJECTS_FAILURE = 'GET_ALL_PROJECTS_FAILURE';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const CREATE_PROJECT_FAILURE = 'CREATE_PROJECT_FAILURE';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';



export const QUESTIONNAIRE_SUCCESS = 'QUESTIONNAIRE_SUCCESS';
export const QUESTIONNAIRE_FAILURE = 'QUESTIONNAIRE_FAILURE';

export const PASSWORD_FORGOT_SUCCESS = 'PASSWORD_FORGOT_SUCCESS';
export const PASSWORD_FORGOT_FAILURE = 'PASSWORD_FORGOT_FAILURE';

export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';

export const GET_ALL_COMMENTS_SUCCESS = 'GET_ALL_COMMENTS_SUCCESS';
export const GET_ALL_COMMENTS_FAILURE = 'GET_ALL_COMMENTS_FAILURE';

export const GET_ALL_DEVELOPMENT_STAGES = 'GET_ALL_DEVELOPMENT_STAGES';
export const CHANGE_STAUS_OF_NODE = "CHANGE_STAUS_OF_NODE";

